FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod.debug go.mod
COPY debug_otlp_input.go .

RUN go mod tidy && go build -o debug-otlp debug_otlp_input.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/

COPY --from=builder /app/debug-otlp .

EXPOSE 4040

CMD ["./debug-otlp"]